Map<String, dynamic> periodMapping = {
  "live": "live",
  "1d": "oneDay",
  "1w": "oneWeek",
  "1m": "oneMonth",
  "3m": "threeMonths",
  "ytd": "ytd",
  "1y": "oneYear",
  "all": "allData",
};

List<Map<String, String>> states = [
  {'name': 'Alabama', 'abbr': 'AL'},
  {'name': 'Alaska', 'abbr': 'AK'},
  {'name': 'Arizona', 'abbr': 'AZ'},
  {'name': 'Arkansas', 'abbr': 'AR'},
  {'name': 'California', 'abbr': 'CA'},
  {'name': 'Colorado', 'abbr': 'CO'},
  {'name': 'Connecticut', 'abbr': 'CT'},
  {'name': 'Delaware', 'abbr': 'DE'},
  {'name': 'Florida', 'abbr': 'FL'},
  {'name': 'Georgia', 'abbr': 'GA'},
  {'name': 'Hawaii', 'abbr': 'HI'},
  {'name': 'Idaho', 'abbr': 'ID'},
  {'name': 'Illinois', 'abbr': 'IL'},
  {'name': 'Indiana', 'abbr': 'IN'},
  {'name': 'Iowa', 'abbr': 'IA'},
  {'name': 'Kansas', 'abbr': 'KS'},
  {'name': 'Kentucky', 'abbr': 'KY'},
  {'name': 'Louisiana', 'abbr': 'LA'},
  {'name': 'Maine', 'abbr': 'ME'},
  {'name': 'Maryland', 'abbr': 'MD'},
  {'name': 'Massachusetts', 'abbr': 'MA'},
  {'name': 'Michigan', 'abbr': 'MI'},
  {'name': 'Minnesota', 'abbr': 'MN'},
  {'name': 'Mississippi', 'abbr': 'MS'},
  {'name': 'Missouri', 'abbr': 'MO'},
  {'name': 'Montana', 'abbr': 'MT'},
  {'name': 'Nebraska', 'abbr': 'NE'},
  {'name': 'Nevada', 'abbr': 'NV'},
  {'name': 'New Hampshire', 'abbr': 'NH'},
  {'name': 'New Jersey', 'abbr': 'NJ'},
  {'name': 'New Mexico', 'abbr': 'NM'},
  {'name': 'New York', 'abbr': 'NY'},
  {'name': 'North Carolina', 'abbr': 'NC'},
  {'name': 'North Dakota', 'abbr': 'ND'},
  {'name': 'Ohio', 'abbr': 'OH'},
  {'name': 'Oklahoma', 'abbr': 'OK'},
  {'name': 'Oregon', 'abbr': 'OR'},
  {'name': 'Pennsylvania', 'abbr': 'PA'},
  {'name': 'Rhode Island', 'abbr': 'RI'},
  {'name': 'South Carolina', 'abbr': 'SC'},
  {'name': 'South Dakota', 'abbr': 'SD'},
  {'name': 'Tennessee', 'abbr': 'TN'},
  {'name': 'Texas', 'abbr': 'TX'},
  {'name': 'Utah', 'abbr': 'UT'},
  {'name': 'Vermont', 'abbr': 'VT'},
  {'name': 'Virginia', 'abbr': 'VA'},
  {'name': 'Washington', 'abbr': 'WA'},
  {'name': 'West Virginia', 'abbr': 'WV'},
  {'name': 'Wisconsin', 'abbr': 'WI'},
  {'name': 'Wyoming', 'abbr': 'WY'},
];

List<Map<String, String>> countries = [
  {'name': 'Afghanistan', 'abbr': 'AF', 'emoji': '🇦🇫'},
  {'name': 'Albania', 'abbr': 'AL', 'emoji': '🇦🇱'},
  {'name': 'Algeria', 'abbr': 'DZ', 'emoji': '🇩🇿'},
  {'name': 'Andorra', 'abbr': 'AD', 'emoji': '🇦🇩'},
  {'name': 'Angola', 'abbr': 'AO', 'emoji': '🇦🇴'},
  {'name': 'Antigua and Barbuda', 'abbr': 'AG', 'emoji': '🇦🇬'},
  {'name': 'Argentina', 'abbr': 'AR', 'emoji': '🇦🇷'},
  {'name': 'Armenia', 'abbr': 'AM', 'emoji': '🇦🇲'},
  {'name': 'Australia', 'abbr': 'AU', 'emoji': '🇦🇺'},
  {'name': 'Austria', 'abbr': 'AT', 'emoji': '🇦🇹'},
  {'name': 'Azerbaijan', 'abbr': 'AZ', 'emoji': '🇦🇿'},
  {'name': 'Bahamas', 'abbr': 'BS', 'emoji': '🇧🇸'},
  {'name': 'Bahrain', 'abbr': 'BH', 'emoji': '🇧🇭'},
  {'name': 'Bangladesh', 'abbr': 'BD', 'emoji': '🇧🇩'},
  {'name': 'Barbados', 'abbr': 'BB', 'emoji': '🇧🇧'},
  {'name': 'Belarus', 'abbr': 'BY', 'emoji': '🇧🇾'},
  {'name': 'Belgium', 'abbr': 'BE', 'emoji': '🇧🇪'},
  {'name': 'Belize', 'abbr': 'BZ', 'emoji': '🇧🇿'},
  {'name': 'Benin', 'abbr': 'BJ', 'emoji': '🇧🇯'},
  {'name': 'Bhutan', 'abbr': 'BT', 'emoji': '🇧🇹'},
  {'name': 'Bolivia', 'abbr': 'BO', 'emoji': '🇧🇴'},
  {'name': 'Bosnia and Herzegovina', 'abbr': 'BA', 'emoji': '🇧🇦'},
  {'name': 'Botswana', 'abbr': 'BW', 'emoji': '🇧🇼'},
  {'name': 'Brazil', 'abbr': 'BR', 'emoji': '🇧🇷'},
  {'name': 'Brunei', 'abbr': 'BN', 'emoji': '🇧🇳'},
  {'name': 'Bulgaria', 'abbr': 'BG', 'emoji': '🇧🇬'},
  {'name': 'Burkina Faso', 'abbr': 'BF', 'emoji': '🇧🇫'},
  {'name': 'Burundi', 'abbr': 'BI', 'emoji': '🇧🇮'},
  {'name': 'Cabo Verde', 'abbr': 'CV', 'emoji': '🇨🇻'},
  {'name': 'Cambodia', 'abbr': 'KH', 'emoji': '🇰🇭'},
  {'name': 'Cameroon', 'abbr': 'CM', 'emoji': '🇨🇲'},
  {'name': 'Canada', 'abbr': 'CA', 'emoji': '🇨🇦'},
  {'name': 'Central African Republic', 'abbr': 'CF', 'emoji': '🇨🇫'},
  {'name': 'Chad', 'abbr': 'TD', 'emoji': '🇹🇩'},
  {'name': 'Chile', 'abbr': 'CL', 'emoji': '🇨🇱'},
  {'name': 'China', 'abbr': 'CN', 'emoji': '🇨🇳'},
  {'name': 'Colombia', 'abbr': 'CO', 'emoji': '🇨🇴'},
  {'name': 'Comoros', 'abbr': 'KM', 'emoji': '🇰🇲'},
  {'name': 'Congo', 'abbr': 'CG', 'emoji': '🇨🇬'},
  {'name': 'Costa Rica', 'abbr': 'CR', 'emoji': '🇨🇷'},
  {'name': 'Croatia', 'abbr': 'HR', 'emoji': '🇭🇷'},
  {'name': 'Cuba', 'abbr': 'CU', 'emoji': '🇨🇺'},
  {'name': 'Cyprus', 'abbr': 'CY', 'emoji': '🇨🇾'},
  {'name': 'Czech Republic', 'abbr': 'CZ', 'emoji': '🇨🇿'},
  {'name': 'Denmark', 'abbr': 'DK', 'emoji': '🇩🇰'},
  {'name': 'Djibouti', 'abbr': 'DJ', 'emoji': '🇩🇯'},
  {'name': 'Dominica', 'abbr': 'DM', 'emoji': '🇩🇲'},
  {'name': 'Dominican Republic', 'abbr': 'DO', 'emoji': '🇩🇴'},
  {'name': 'East Timor', 'abbr': 'TL', 'emoji': '🇹🇱'},
  {'name': 'Ecuador', 'abbr': 'EC', 'emoji': '🇪🇨'},
  {'name': 'Egypt', 'abbr': 'EG', 'emoji': '🇪🇬'},
  {'name': 'El Salvador', 'abbr': 'SV', 'emoji': '🇸🇻'},
  {'name': 'Equatorial Guinea', 'abbr': 'GQ', 'emoji': '🇬🇶'},
  {'name': 'Eritrea', 'abbr': 'ER', 'emoji': '🇪🇷'},
  {'name': 'Estonia', 'abbr': 'EE', 'emoji': '🇪🇪'},
  {'name': 'Eswatini', 'abbr': 'SZ', 'emoji': '🇸🇿'},
  {'name': 'Ethiopia', 'abbr': 'ET', 'emoji': '🇪🇹'},
  {'name': 'Fiji', 'abbr': 'FJ', 'emoji': '🇫🇯'},
  {'name': 'Finland', 'abbr': 'FI', 'emoji': '🇫🇮'},
  {'name': 'France', 'abbr': 'FR', 'emoji': '🇫🇷'},
  {'name': 'Gabon', 'abbr': 'GA', 'emoji': '🇬🇦'},
  {'name': 'Gambia', 'abbr': 'GM', 'emoji': '🇬🇲'},
  {'name': 'Georgia', 'abbr': 'GE', 'emoji': '🇬🇪'},
  {'name': 'Germany', 'abbr': 'DE', 'emoji': '🇩🇪'},
  {'name': 'Ghana', 'abbr': 'GH', 'emoji': '🇬🇭'},
  {'name': 'Greece', 'abbr': 'GR', 'emoji': '🇬🇷'},
  {'name': 'Grenada', 'abbr': 'GD', 'emoji': '🇬🇩'},
  {'name': 'Guatemala', 'abbr': 'GT', 'emoji': '🇬🇹'},
  {'name': 'Guinea', 'abbr': 'GN', 'emoji': '🇬🇳'},
  {'name': 'Guinea-Bissau', 'abbr': 'GW', 'emoji': '🇬🇼'},
  {'name': 'Guyana', 'abbr': 'GY', 'emoji': '🇬🇾'},
  {'name': 'Haiti', 'abbr': 'HT', 'emoji': '🇭🇹'},
  {'name': 'Honduras', 'abbr': 'HN', 'emoji': '🇭🇳'},
  {'name': 'Hungary', 'abbr': 'HU', 'emoji': '🇭🇺'},
  {'name': 'Iceland', 'abbr': 'IS', 'emoji': '🇮🇸'},
  {'name': 'India', 'abbr': 'IN', 'emoji': '🇮🇳'},
  {'name': 'Indonesia', 'abbr': 'ID', 'emoji': '🇮🇩'},
  {'name': 'Iran', 'abbr': 'IR', 'emoji': '🇮🇷'},
  {'name': 'Iraq', 'abbr': 'IQ', 'emoji': '🇮🇶'},
  {'name': 'Ireland', 'abbr': 'IE', 'emoji': '🇮🇪'},
  {'name': 'Israel', 'abbr': 'IL', 'emoji': '🇮🇱'},
  {'name': 'Italy', 'abbr': 'IT', 'emoji': '🇮🇹'},
  {'name': 'Jamaica', 'abbr': 'JM', 'emoji': '🇯🇲'},
  {'name': 'Japan', 'abbr': 'JP', 'emoji': '🇯🇵'},
  {'name': 'Jordan', 'abbr': 'JO', 'emoji': '🇯🇴'},
  {'name': 'Kazakhstan', 'abbr': 'KZ', 'emoji': '🇰🇿'},
  {'name': 'Kenya', 'abbr': 'KE', 'emoji': '🇰🇪'},
  {'name': 'Kiribati', 'abbr': 'KI', 'emoji': '🇰🇮'},
  {'name': 'Korea, North', 'abbr': 'KP', 'emoji': '🇰🇵'},
  {'name': 'Korea, South', 'abbr': 'KR', 'emoji': '🇰🇷'},
  {'name': 'Kosovo', 'abbr': 'XK', 'emoji': '🇽🇰'},
  {'name': 'Kuwait', 'abbr': 'KW', 'emoji': '🇰🇼'},
  {'name': 'Kyrgyzstan', 'abbr': 'KG', 'emoji': '🇰🇬'},
  {'name': 'Laos', 'abbr': 'LA', 'emoji': '🇱🇦'},
  {'name': 'Latvia', 'abbr': 'LV', 'emoji': '🇱🇻'},
  {'name': 'Lebanon', 'abbr': 'LB', 'emoji': '🇱🇧'},
  {'name': 'Lesotho', 'abbr': 'LS', 'emoji': '🇱🇸'},
  {'name': 'Liberia', 'abbr': 'LR', 'emoji': '🇱🇷'},
  {'name': 'Libya', 'abbr': 'LY', 'emoji': '🇱🇾'},
  {'name': 'Liechtenstein', 'abbr': 'LI', 'emoji': '🇱🇮'},
  {'name': 'Lithuania', 'abbr': 'LT', 'emoji': '🇱🇹'},
  {'name': 'Luxembourg', 'abbr': 'LU', 'emoji': '🇱🇺'},
  {'name': 'Madagascar', 'abbr': 'MG', 'emoji': '🇲🇬'},
  {'name': 'Malawi', 'abbr': 'MW', 'emoji': '🇲🇼'},
  {'name': 'Malaysia', 'abbr': 'MY', 'emoji': '🇲🇾'},
  {'name': 'Maldives', 'abbr': 'MV', 'emoji': '🇲🇻'},
  {'name': 'Mali', 'abbr': 'ML', 'emoji': '🇲🇱'},
  {'name': 'Malta', 'abbr': 'MT', 'emoji': '🇲🇹'},
  {'name': 'Marshall Islands', 'abbr': 'MH', 'emoji': '🇲🇭'},
  {'name': 'Mauritania', 'abbr': 'MR', 'emoji': '🇲🇷'},
  {'name': 'Mauritius', 'abbr': 'MU', 'emoji': '🇲🇺'},
  {'name': 'Mexico', 'abbr': 'MX', 'emoji': '🇲🇽'},
  {'name': 'Micronesia', 'abbr': 'FM', 'emoji': '🇫🇲'},
  {'name': 'Moldova', 'abbr': 'MD', 'emoji': '🇲🇩'},
  {'name': 'Monaco', 'abbr': 'MC', 'emoji': '🇲🇨'},
  {'name': 'Mongolia', 'abbr': 'MN', 'emoji': '🇲🇳'},
  {'name': 'Montenegro', 'abbr': 'ME', 'emoji': '🇲🇪'},
  {'name': 'Morocco', 'abbr': 'MA', 'emoji': '🇲🇦'},
  {'name': 'Mozambique', 'abbr': 'MZ', 'emoji': '🇲🇿'},
  {'name': 'Myanmar', 'abbr': 'MM', 'emoji': '🇲🇲'},
  {'name': 'Namibia', 'abbr': 'NA', 'emoji': '🇳🇦'},
  {'name': 'Nauru', 'abbr': 'NR', 'emoji': '🇳🇷'},
  {'name': 'Nepal', 'abbr': 'NP', 'emoji': '🇳🇵'},
  {'name': 'Netherlands', 'abbr': 'NL', 'emoji': '🇳🇱'},
  {'name': 'New Zealand', 'abbr': 'NZ', 'emoji': '🇳🇿'},
  {'name': 'Nicaragua', 'abbr': 'NI', 'emoji': '🇳🇮'},
  {'name': 'Niger', 'abbr': 'NE', 'emoji': '🇳🇪'},
  {'name': 'Nigeria', 'abbr': 'NG', 'emoji': '🇳🇬'},
  {'name': 'North Macedonia', 'abbr': 'MK', 'emoji': '🇲🇰'},
  {'name': 'Norway', 'abbr': 'NO', 'emoji': '🇳🇴'},
  {'name': 'Oman', 'abbr': 'OM', 'emoji': '🇴🇲'},
  {'name': 'Pakistan', 'abbr': 'PK', 'emoji': '🇵🇰'},
  {'name': 'Palau', 'abbr': 'PW', 'emoji': '🇵🇼'},
  {'name': 'Panama', 'abbr': 'PA', 'emoji': '🇵🇦'},
  {'name': 'Papua New Guinea', 'abbr': 'PG', 'emoji': '🇵🇬'},
  {'name': 'Paraguay', 'abbr': 'PY', 'emoji': '🇵🇾'},
  {'name': 'Peru', 'abbr': 'PE', 'emoji': '🇵🇪'},
  {'name': 'Philippines', 'abbr': 'PH', 'emoji': '🇵🇭'},
  {'name': 'Poland', 'abbr': 'PL', 'emoji': '🇵🇱'},
  {'name': 'Portugal', 'abbr': 'PT', 'emoji': '🇵🇹'},
  {'name': 'Qatar', 'abbr': 'QA', 'emoji': '🇶🇦'},
  {'name': 'Romania', 'abbr': 'RO', 'emoji': '🇷🇴'},
  {'name': 'Russia', 'abbr': 'RU', 'emoji': '🇷🇺'},
  {'name': 'Rwanda', 'abbr': 'RW', 'emoji': '🇷🇼'},
  {'name': 'Saint Kitts and Nevis', 'abbr': 'KN', 'emoji': '🇰🇳'},
  {'name': 'Saint Lucia', 'abbr': 'LC', 'emoji': '🇱🇨'},
  {'name': 'Saint Vincent and the Grenadines', 'abbr': 'VC', 'emoji': '🇻🇨'},
  {'name': 'Samoa', 'abbr': 'WS', 'emoji': '🇼🇸'},
  {'name': 'San Marino', 'abbr': 'SM', 'emoji': '🇸🇲'},
  {'name': 'Sao Tome and Principe', 'abbr': 'ST', 'emoji': '🇸🇹'},
  {'name': 'Saudi Arabia', 'abbr': 'SA', 'emoji': '🇸🇦'},
  {'name': 'Senegal', 'abbr': 'SN', 'emoji': '🇸🇳'},
  {'name': 'Serbia', 'abbr': 'RS', 'emoji': '🇷🇸'},
  {'name': 'Seychelles', 'abbr': 'SC', 'emoji': '🇸🇨'},
  {'name': 'Sierra Leone', 'abbr': 'SL', 'emoji': '🇸🇱'},
  {'name': 'Singapore', 'abbr': 'SG', 'emoji': '🇸🇬'},
  {'name': 'Slovakia', 'abbr': 'SK', 'emoji': '🇸🇰'},
  {'name': 'Slovenia', 'abbr': 'SI', 'emoji': '🇸🇮'},
  {'name': 'Solomon Islands', 'abbr': 'SB', 'emoji': '🇸🇧'},
  {'name': 'Somalia', 'abbr': 'SO', 'emoji': '🇸🇴'},
  {'name': 'South Africa', 'abbr': 'ZA', 'emoji': '🇿🇦'},
  {'name': 'South Sudan', 'abbr': 'SS', 'emoji': '🇸🇸'},
  {'name': 'Spain', 'abbr': 'ES', 'emoji': '🇪🇸'},
  {'name': 'Sri Lanka', 'abbr': 'LK', 'emoji': '🇱🇰'},
  {'name': 'Sudan', 'abbr': 'SD', 'emoji': '🇸🇩'},
  {'name': 'Suriname', 'abbr': 'SR', 'emoji': '🇸🇷'},
  {'name': 'Sweden', 'abbr': 'SE', 'emoji': '🇸🇪'},
  {'name': 'Switzerland', 'abbr': 'CH', 'emoji': '🇨🇭'},
  {'name': 'Syria', 'abbr': 'SY', 'emoji': '🇸🇾'},
  {'name': 'Taiwan', 'abbr': 'TW', 'emoji': '🇹🇼'},
  {'name': 'Tajikistan', 'abbr': 'TJ', 'emoji': '🇹🇯'},
  {'name': 'Tanzania', 'abbr': 'TZ', 'emoji': '🇹🇿'},
  {'name': 'Thailand', 'abbr': 'TH', 'emoji': '🇹🇭'},
  {'name': 'Togo', 'abbr': 'TG', 'emoji': '🇹🇬'},
  {'name': 'Tonga', 'abbr': 'TO', 'emoji': '🇹🇴'},
  {'name': 'Trinidad and Tobago', 'abbr': 'TT', 'emoji': '🇹🇹'},
  {'name': 'Tunisia', 'abbr': 'TN', 'emoji': '🇹🇳'},
  {'name': 'Turkey', 'abbr': 'TR', 'emoji': '🇹🇷'},
  {'name': 'Turkmenistan', 'abbr': 'TM', 'emoji': '🇹🇲'},
  {'name': 'Tuvalu', 'abbr': 'TV', 'emoji': '🇹🇻'},
  {'name': 'Uganda', 'abbr': 'UG', 'emoji': '🇺🇬'},
  {'name': 'Ukraine', 'abbr': 'UA', 'emoji': '🇺🇦'},
  {'name': 'United Arab Emirates', 'abbr': 'AE', 'emoji': '🇦🇪'},
  {'name': 'United Kingdom', 'abbr': 'GB', 'emoji': '🇬🇧'},
  {'name': 'United States', 'abbr': 'US', 'emoji': '🇺🇸'},
  {'name': 'Uruguay', 'abbr': 'UY', 'emoji': '🇺🇾'},
  {'name': 'Uzbekistan', 'abbr': 'UZ', 'emoji': '🇺🇿'},
  {'name': 'Vanuatu', 'abbr': 'VU', 'emoji': '🇻🇺'},
  {'name': 'Vatican City', 'abbr': 'VA', 'emoji': '🇻🇦'},
  {'name': 'Venezuela', 'abbr': 'VE', 'emoji': '🇻🇪'},
  {'name': 'Vietnam', 'abbr': 'VN', 'emoji': '🇻🇳'},
  {'name': 'Yemen', 'abbr': 'YE', 'emoji': '🇾🇪'},
  {'name': 'Zambia', 'abbr': 'ZM', 'emoji': '🇿🇲'},
  {'name': 'Zimbabwe', 'abbr': 'ZW', 'emoji': '🇿🇼'}
];