// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJD_StSHKZxRQJgsgOMm4ifUmjVDA0Pg',
    appId: '1:231022961791:web:a2b62ffc63dc9c03b58b4a',
    messagingSenderId: '231022961791',
    projectId: 'royal-stock-exchange',
    authDomain: 'royal-stock-exchange.firebaseapp.com',
    storageBucket: 'royal-stock-exchange.appspot.com',
    measurementId: 'G-BDHRPQN841',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5c5Ns6KWHpf9jM_gM4NDe7nAd2OECSrw',
    appId: '1:231022961791:android:f34687269c4e7853b58b4a',
    messagingSenderId: '231022961791',
    projectId: 'royal-stock-exchange',
    storageBucket: 'royal-stock-exchange.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiWWmf5vuTF_kN3_WUF5eunn3kfQg3yvQ',
    appId: '1:231022961791:ios:9215f4a18316e6e9b58b4a',
    messagingSenderId: '231022961791',
    projectId: 'royal-stock-exchange',
    storageBucket: 'royal-stock-exchange.appspot.com',
    iosClientId: '231022961791-ipn2qe5dhhphvd6ieibajd097pv0ebur.apps.googleusercontent.com',
    iosBundleId: 'com.example.rse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiWWmf5vuTF_kN3_WUF5eunn3kfQg3yvQ',
    appId: '1:231022961791:ios:ad34ad590fecd231b58b4a',
    messagingSenderId: '231022961791',
    projectId: 'royal-stock-exchange',
    storageBucket: 'royal-stock-exchange.appspot.com',
    iosClientId: '231022961791-28mgg4ltvdu5jq5lvq85kq7e184uprme.apps.googleusercontent.com',
    iosBundleId: 'com.example.rse.RunnerTests',
  );
}
