name: Configure remote config

on: [ push ]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  get-remote-config:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - uses: actions/checkout@v2

      - name: Get remote config
        uses: w9jds/firebase-action@master
        with:
          args: firebase remoteconfig:get --project=${{ vars.FIREBASE_PROJECT_ID }} --output ./ci/config.json
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_TOKEN }}

  update:
    runs-on: ubuntu-latest
    needs: get-remote-config
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Publish
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          BUILD_VERSION: ${{ github.run_number }}
        run: |
          python ./ci/ci.py --action=publish